"""Shared Python building blocks for Cortex services."""

from cortex_shared.config import CortexConfig, load_config
from cortex_shared.metrics import metrics_app, record_stage_tokens, record_request
from cortex_shared.otel import setup_otel
from cortex_shared.types import (
    AuditRecord,
    Concept,
    ConceptDetail,
    ConceptListItem,
    ConnectorStatus,
    ContextFragment,
    EdgeState,
    Entity,
    EntityAuditAppearance,
    EntityLineage,
    EntityListItem,
    EntityListResponse,
    EntityRef,
    ExtractedConcept,
    ExtractedRelation,
    ExtractionResult,
    GraphAuditRow,
    IdentityContext,
    IngestEvent,
    IngestionRun,
    IngestionRunStatus,
    Neighbour,
    RelationshipEdge,
    RelationshipType,
    RetrievalRequest,
    RetrievalResponse,
    StageUsage,
    TraverseRequest,
    TraverseResponse,
    UsageEnvelope,
    VectorSearchHit,
    VectorSearchResponse,
)

__all__ = [
    "AuditRecord",
    "Concept",
    "ConceptDetail",
    "ConceptListItem",
    "ConnectorStatus",
    "ContextFragment",
    "EdgeState",
    "Entity",
    "EntityAuditAppearance",
    "EntityLineage",
    "EntityListItem",
    "EntityListResponse",
    "EntityRef",
    "ExtractedConcept",
    "ExtractedRelation",
    "ExtractionResult",
    "GraphAuditRow",
    "CortexConfig",
    "IdentityContext",
    "IngestEvent",
    "IngestionRun",
    "IngestionRunStatus",
    "Neighbour",
    "RelationshipEdge",
    "RelationshipType",
    "RetrievalRequest",
    "RetrievalResponse",
    "StageUsage",
    "TraverseRequest",
    "TraverseResponse",
    "UsageEnvelope",
    "VectorSearchHit",
    "VectorSearchResponse",
    "load_config",
    "metrics_app",
    "record_request",
    "record_stage_tokens",
    "setup_otel",
]
